/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}", "./screens/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "on-surface-variant": "#b9cbbd",
        "on-secondary-fixed": "#001f26",
        "on-primary-fixed-variant": "#005231",
        "error-container": "#93000a",
        "tertiary-container": "#ffd6d8",
        "surface-container-lowest": "#0a0d1c",
        "secondary-fixed-dim": "#00d9ff",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#00e290",
        "on-primary-fixed": "#002111",
        "surface-container-low": "#171b2a",
        "on-tertiary": "#67001c",
        "error": "#ffb4ab",
        "inverse-surface": "#dfe1f6",
        "surface-dim": "#0f1321",
        "on-secondary-container": "#005b6c",
        "outline": "#849588",
        "primary-container": "#00ffa3",
        "surface-variant": "#303444",
        "on-background": "#dfe1f6",
        "tertiary": "#fffbff",
        "secondary": "#aeecff",
        "secondary-fixed": "#aeecff",
        "surface": "#0f1321",
        "background": "#0f1321",
        "surface-container": "#1b1f2e",
        "on-secondary": "#003641",
        "inverse-primary": "#006d43",
        "secondary-container": "#00d9ff",
        "on-primary": "#003920",
        "tertiary-fixed": "#ffdadb",
        "surface-container-highest": "#303444",
        "inverse-on-surface": "#2c303f",
        "on-tertiary-fixed": "#40000e",
        "on-tertiary-fixed-variant": "#91002b",
        "surface-container-high": "#262939",
        "surface-bright": "#353849",
        "on-tertiary-container": "#c6003e",
        "tertiary-fixed-dim": "#ffb2b7",
        "surface-tint": "#00e290",
        "outline-variant": "#3a4a3f",
        "primary": "#f5fff5",
        "on-surface": "#dfe1f6",
        "on-primary-container": "#007146",
        "on-secondary-fixed-variant": "#004e5d",
        "primary-fixed": "#52ffac"
      },
      spacing: {
        "md": "24px",
        "margin": "24px",
        "xs": "8px",
        "gutter": "16px",
        "xl": "64px",
        "base": "4px",
        "sm": "16px",
        "lg": "40px"
      },
      fontFamily: {
        "data-mono": ["JetBrains Mono"],
        "headline-lg-mobile": ["Sora"],
        "headline-md": ["Sora"],
        "body-lg": ["Geist"],
        "headline-lg": ["Sora"],
        "body-md": ["Geist"],
        "label-caps": ["JetBrains Mono"],
        "display-lg": ["Sora"]
      }
    }
  },
  plugins: [],
}
